steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - hellopips
      - --source=./kmcloudbuild
      - --trigger-http
      - --runtime=python37
      - --allow-unauthenticated
